---
title: "Sales Dashboard Prototype"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r c8 setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(DT)
library(tidyverse)
library(plotly)
library(shiny)
```

```{r c7, message=FALSE, warning=FALSE, include=FALSE}
source("data_processing.R")
```

Sidebar {.sidebar}
=======================================================================

This dashboard displays Pivot Health's sales data with a collection of clickable tabs and visualizations. 

-----------------------

Below are filters that drive the visualizations in each of the tabs:

```{r}
selectInput("duration", label = h4("Select Plan Duration:"), choices = list("All"=1,"Yearly"=2, "90 Day"=3), selected=1)
```

```{r}
selectInput("plan", label = h4("Select Plan Type:"), choices = list("All"=1,"Economy"=2, "Standard"=3, "Deluxe"=4, "Choice" = 5), selected =1)
```

```{r}
floor <- min(plan_table$Date)
ceiling <- max(plan_table$Date)

dateRangeInput("trend", label = h4("Select date range:"),
               start = floor,
               end = ceiling,
               min = floor,
               max = ceiling)
```



Web Sales
=======================================================================


Column {data-width=400}
-----------------------------------------------------------------------

### {.value-box}
```{r}
#renderValueBox({
  valueBox(
    value = paste("Web Sales Snapshot", "-", "July 2, 2017")
    #caption = h4("The graphs below show the current snapshot of web sales by product"),
    #icon = "fa-area-chart"
  )
#})
```


### 

```{r}
latest_day <- max(web_plans$Date)


g1 <- plan_table %>%
      filter(Date == latest_day &
             Tab == "web") %>%
      ggplot(aes(x = Plan, y = Sales, fill = Plan)) + geom_bar(stat="identity", colour = "#1e1e1e") + scale_fill_brewer() + coord_flip() + theme(panel.background = element_rect(fill = "#BEC2C4")) + scale_x_discrete() + ggtitle("Web sales by product - 07/02/2017")
ggplotly(g1)
```



### 

```{r}
g1 <- plan_table %>%
      filter(months(Date) == months(latest_day) & 
             Tab == "web") %>%
      ggplot(aes(x = Plan, y = Sales, fill = Plan)) + geom_bar(stat="identity", colour = "#1e1e1e") + scale_fill_brewer() + coord_flip() + theme(panel.background = element_rect(fill = "#BEC2C4")) + ggtitle("Web sales by product - month of July 2017")

ggplotly(g1)
```


Column {data-width=400}
-----------------------------------------------------------------------

### {.value-box}
```{r}
#renderValueBox({
  valueBox(
    value = "Web Sales by State - YTD"
  )
#})
```

### 

```{r}
crimes <- data.frame(state = tolower(rownames(USArrests)), USArrests)
crimesm <- tidyr::gather(crimes, variable, value, -state)
states_map <- map_data("state")
g <- ggplot(crimesm, aes(map_id = state)) +
  geom_map(aes(fill = value), map = states_map) +
  expand_limits(x = states_map$long, y = states_map$lat) + theme_void() 
ggplotly(g)
```



### {.value-box}
```{r}
#renderValueBox({
  valueBox(
    value = "Web sales over time by product"
  )
#})
```


### 

```{r}
plans_expanded <- data.frame(
  Date = rep(plan_table$Date, plan_table$Sales),
  Plan = rep(plan_table$Plan, plan_table$Sales),
  Duration = rep(plan_table$Duration, plan_table$Sales),
  Tab = rep(plan_table$Tab, plan_table$Sales)
)

g1 <- plans_expanded %>%
      filter(Tab == "web") %>%
      ggplot(aes(x = Date, fill = Plan)) + scale_fill_brewer() + geom_area(stat="bin", colour = "#1e1e1e")  + theme(panel.background = element_rect(fill = "#BEC2C4")) 
ggplotly(g1)
```




Adroit Sales
=======================================================================

Column {data-width=400}
-----------------------------------------------------------------------

### Chart H

### Chart I

Column {data-width=400}
-----------------------------------------------------------------------

### Chart J


### Chart K

Assistant Agencies
=======================================================================
